### ISSUE TITLE
Startup fails due to java.sql.SQLException: Too many connections

### ISSUE THREAD

**Issue by muellerdo** [qbicsoftware/variantstore-service#20]
Heyho QBiC team,

when running a previously packaged jar, I got the following error message, now.

It is interesting to know that I was able to successfully run the package a few month ago.
Therefore, maybe it is related to some of the latest changes?

Additionally, I checked the process list in the database and saw some idled processes.
Maybe, there is a connection which is missing a close() ?

Here is the error log:
```
Building variantstore
Step 1/4 : FROM openjdk:8u171-alpine3.7
 ---> 1caad94162ef
Step 2/4 : RUN apk --no-cache add curl
 ---> Using cache
 ---> 191fd9264836
Step 3/4 : COPY target/variantstore-0.6-SNAPSHOT.jar oncostore.jar
 ---> 4d8554fd1b68
Step 4/4 : CMD java ${JAVA_OPTS} -jar oncostore.jar
 ---> Running in 0666ca9df8d8
Removing intermediate container 0666ca9df8d8
 ---> e351fe4cc663

Successfully built e351fe4cc663
Successfully tagged variantstore_variantstore:latest
WARNING: Image for service variantstore was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating variantstore_db ... done
Creating variantstore_variantstore_1 ... done
Attaching to variantstore_db, variantstore_variantstore_1
db_1            | 2020-05-29 09:10:13+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.3.23+maria~bionic started.
db_1            | 2020-05-29 09:10:14+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
db_1            | 2020-05-29 09:10:14+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.3.23+maria~bionic started.
db_1            | 2020-05-29 09:10:14+00:00 [Note] [Entrypoint]: Initializing database files
db_1            | 
db_1            | 
db_1            | PLEASE REMEMBER TO SET A PASSWORD FOR THE MariaDB root USER !
db_1            | To do so, start the server, then issue the following commands:
db_1            | 
db_1            | '/usr/bin/mysqladmin' -u root password 'new-password'
db_1            | '/usr/bin/mysqladmin' -u root -h  password 'new-password'
db_1            | 
db_1            | Alternatively you can run:
db_1            | '/usr/bin/mysql_secure_installation'
db_1            | 
db_1            | which will also give you the option of removing the test
db_1            | databases and anonymous user created by default.  This is
db_1            | strongly recommended for production servers.
db_1            | 
db_1            | See the MariaDB Knowledgebase at http://mariadb.com/kb or the
db_1            | MySQL manual for more instructions.
db_1            | 
db_1            | Please report any problems at http://mariadb.org/jira
db_1            | 
db_1            | The latest information about MariaDB is available at http://mariadb.org/.
db_1            | You can find additional information about the MySQL part at:
db_1            | http://dev.mysql.com
db_1            | Consider joining MariaDB's strong and vibrant community:
db_1            | https://mariadb.org/get-involved/
db_1            | 
db_1            | 2020-05-29 09:10:17+00:00 [Note] [Entrypoint]: Database files initialized
db_1            | 2020-05-29 09:10:17+00:00 [Note] [Entrypoint]: Starting temporary server
db_1            | 2020-05-29 09:10:17+00:00 [Note] [Entrypoint]: Waiting for server startup
db_1            | 2020-05-29  9:10:17 0 [Note] mysqld (mysqld 10.3.23-MariaDB-1:10.3.23+maria~bionic) starting as process 124 ...
db_1            | 2020-05-29  9:10:17 0 [Note] InnoDB: Using Linux native AIO
db_1            | 2020-05-29  9:10:17 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1            | 2020-05-29  9:10:17 0 [Note] InnoDB: Uses event mutexes
db_1            | 2020-05-29  9:10:17 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
db_1            | 2020-05-29  9:10:17 0 [Note] InnoDB: Number of pools: 1
db_1            | 2020-05-29  9:10:17 0 [Note] InnoDB: Using SSE2 crc32 instructions
db_1            | 2020-05-29  9:10:17 0 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M
db_1            | 2020-05-29  9:10:17 0 [Note] InnoDB: Completed initialization of buffer pool
db_1            | 2020-05-29  9:10:17 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
db_1            | 2020-05-29  9:10:17 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
db_1            | 2020-05-29  9:10:17 0 [Note] InnoDB: Creating shared tablespace for temporary tables
db_1            | 2020-05-29  9:10:17 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
db_1            | 2020-05-29  9:10:17 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
db_1            | 2020-05-29  9:10:17 0 [Note] InnoDB: Waiting for purge to start
db_1            | 2020-05-29  9:10:17 0 [Note] InnoDB: 10.3.23 started; log sequence number 1625448; transaction id 21
db_1            | 2020-05-29  9:10:17 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
db_1            | 2020-05-29  9:10:17 0 [Note] Plugin 'FEEDBACK' is disabled.
db_1            | 2020-05-29  9:10:17 0 [Note] InnoDB: Buffer pool(s) load completed at 200529  9:10:17
db_1            | 2020-05-29  9:10:17 0 [Warning] 'user' entry 'root@b2d024b89708' ignored in --skip-name-resolve mode.
db_1            | 2020-05-29  9:10:17 0 [Warning] 'user' entry '@b2d024b89708' ignored in --skip-name-resolve mode.
db_1            | 2020-05-29  9:10:17 0 [Warning] 'proxies_priv' entry '@% root@b2d024b89708' ignored in --skip-name-resolve mode.
db_1            | 2020-05-29  9:10:17 0 [Note] Reading of all Master_info entries succeeded
db_1            | 2020-05-29  9:10:17 0 [Note] Added new Master_info '' to hash table
db_1            | 2020-05-29  9:10:17 0 [Note] mysqld: ready for connections.
db_1            | Version: '10.3.23-MariaDB-1:10.3.23+maria~bionic'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  mariadb.org binary distribution
db_1            | 2020-05-29 09:10:18+00:00 [Note] [Entrypoint]: Temporary server started.
db_1            | Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
db_1            | 2020-05-29  9:10:19 10 [Warning] 'proxies_priv' entry '@% root@b2d024b89708' ignored in --skip-name-resolve mode.
db_1            | 2020-05-29 09:10:19+00:00 [Note] [Entrypoint]: Creating database oncostore
db_1            | 
db_1            | 2020-05-29 09:10:19+00:00 [Note] [Entrypoint]: /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/oncostore-init.sql
db_1            | 
db_1            | 
db_1            | 2020-05-29 09:10:19+00:00 [Note] [Entrypoint]: Stopping temporary server
db_1            | 2020-05-29  9:10:19 0 [Note] mysqld (initiated by: root[root] @ localhost []): Normal shutdown
db_1            | 2020-05-29  9:10:19 0 [Note] Event Scheduler: Purging the queue. 0 events
db_1            | 2020-05-29  9:10:19 0 [Note] InnoDB: FTS optimize thread exiting.
db_1            | 2020-05-29  9:10:19 0 [Note] InnoDB: Starting shutdown...
db_1            | 2020-05-29  9:10:19 0 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
db_1            | 2020-05-29  9:10:19 0 [Note] InnoDB: Buffer pool(s) dump completed at 200529  9:10:19
db_1            | 2020-05-29  9:10:20 0 [Note] InnoDB: Shutdown completed; log sequence number 1860732; transaction id 128
db_1            | 2020-05-29  9:10:20 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
db_1            | 2020-05-29  9:10:20 0 [Note] mysqld: Shutdown complete
db_1            | 
db_1            | 2020-05-29 09:10:21+00:00 [Note] [Entrypoint]: Temporary server stopped
db_1            | 
db_1            | 2020-05-29 09:10:21+00:00 [Note] [Entrypoint]: MySQL init process done. Ready for start up.
db_1            | 
db_1            | 2020-05-29  9:10:21 0 [Note] mysqld (mysqld 10.3.23-MariaDB-1:10.3.23+maria~bionic) starting as process 1 ...
db_1            | 2020-05-29  9:10:21 0 [Note] InnoDB: Using Linux native AIO
db_1            | 2020-05-29  9:10:21 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1            | 2020-05-29  9:10:21 0 [Note] InnoDB: Uses event mutexes
db_1            | 2020-05-29  9:10:21 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
db_1            | 2020-05-29  9:10:21 0 [Note] InnoDB: Number of pools: 1
db_1            | 2020-05-29  9:10:21 0 [Note] InnoDB: Using SSE2 crc32 instructions
db_1            | 2020-05-29  9:10:21 0 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M
db_1            | 2020-05-29  9:10:21 0 [Note] InnoDB: Completed initialization of buffer pool
db_1            | 2020-05-29  9:10:21 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
db_1            | 2020-05-29  9:10:21 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
db_1            | 2020-05-29  9:10:21 0 [Note] InnoDB: Creating shared tablespace for temporary tables
db_1            | 2020-05-29  9:10:21 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
db_1            | 2020-05-29  9:10:21 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
db_1            | 2020-05-29  9:10:21 0 [Note] InnoDB: Waiting for purge to start
db_1            | 2020-05-29  9:10:21 0 [Note] InnoDB: 10.3.23 started; log sequence number 1860732; transaction id 130
db_1            | 2020-05-29  9:10:21 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
db_1            | 2020-05-29  9:10:21 0 [Note] Plugin 'FEEDBACK' is disabled.
db_1            | 2020-05-29  9:10:21 0 [Note] Server socket created on IP: '::'.
db_1            | 2020-05-29  9:10:21 0 [Warning] 'proxies_priv' entry '@% root@b2d024b89708' ignored in --skip-name-resolve mode.
db_1            | 2020-05-29  9:10:21 0 [Note] Reading of all Master_info entries succeeded
db_1            | 2020-05-29  9:10:21 0 [Note] Added new Master_info '' to hash table
db_1            | 2020-05-29  9:10:21 0 [Note] mysqld: ready for connections.
db_1            | Version: '10.3.23-MariaDB-1:10.3.23+maria~bionic'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
db_1            | 2020-05-29  9:10:21 0 [Note] InnoDB: Buffer pool(s) load completed at 200529  9:10:21
variantstore_1  | 29.05.2020 09:10:48 [INFO] [Application] - Variantstore started.
variantstore_1  | 09:10:50.643 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 1584ms. Server Running: http://ab91479136fc:8080
variantstore_1  | 09:11:50.366 [pool-2-thread-7] ERROR o.m.jdbc.internal.util.pool.Pool - error initializing pool connection
variantstore_1  | java.sql.SQLException: Too many connections
variantstore_1  | 	at org.mariadb.jdbc.internal.com.read.ReadInitialHandShakePacket.<init>(ReadInitialHandShakePacket.java:92)
variantstore_1  | 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:688)
variantstore_1  | 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:412)
variantstore_1  | 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1124)
variantstore_1  | 	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:560)
variantstore_1  | 	at org.mariadb.jdbc.internal.util.pool.Pool.addConnection(Pool.java:218)
variantstore_1  | 	at org.mariadb.jdbc.internal.util.pool.Pool.<init>(Pool.java:127)
variantstore_1  | 	at org.mariadb.jdbc.internal.util.pool.Pools.retrievePool(Pools.java:53)
variantstore_1  | 	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:171)
variantstore_1  | 	at org.mariadb.jdbc.Driver.connect(Driver.java:92)
variantstore_1  | 	at org.apache.commons.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:55)
variantstore_1  | 	at org.apache.commons.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:355)
variantstore_1  | 	at org.apache.commons.dbcp2.BasicDataSource.validateConnectionFactory(BasicDataSource.java:115)
variantstore_1  | 	at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:665)
variantstore_1  | 	at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:544)
variantstore_1  | 	at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:753)
variantstore_1  | 	at io.micronaut.management.health.indicator.jdbc.JdbcIndicator.lambda$getResult$0(JdbcIndicator.java:85)
variantstore_1  | 	at io.micronaut.core.async.publisher.AsyncSingleResultPublisher$ExecutorServiceSubscription.lambda$request$1(AsyncSingleResultPublisher.java:100)
variantstore_1  | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
variantstore_1  | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
variantstore_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
variantstore_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
variantstore_1  | 	at java.lang.Thread.run(Thread.java:748)
```

Here is the process list from the database:
```
MariaDB [(none)]> show processlist;
+-----+-------------+------------------+-----------+---------+------+--------------------------+------------------+----------+
| Id  | User        | Host             | db        | Command | Time | State                    | Info             | Progress |
+-----+-------------+------------------+-----------+---------+------+--------------------------+------------------+----------+
|   4 | system user |                  | NULL      | Daemon  | NULL | InnoDB purge worker      | NULL             |    0.000 |
|   2 | system user |                  | NULL      | Daemon  | NULL | InnoDB purge worker      | NULL             |    0.000 |
|   1 | system user |                  | NULL      | Daemon  | NULL | InnoDB purge coordinator | NULL             |    0.000 |
|   3 | system user |                  | NULL      | Daemon  | NULL | InnoDB purge worker      | NULL             |    0.000 |
|   5 | system user |                  | NULL      | Daemon  | NULL | InnoDB shutdown handler  | NULL             |    0.000 |
|   9 | root        | localhost        | NULL      | Query   |    0 | Init                     | show processlist |    0.000 |
|  12 | root        | 172.20.0.3:35060 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  13 | root        | 172.20.0.3:35062 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  14 | root        | 172.20.0.3:35064 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  15 | root        | 172.20.0.3:35066 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  16 | root        | 172.20.0.3:35068 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  17 | root        | 172.20.0.3:35070 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  18 | root        | 172.20.0.3:35072 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  19 | root        | 172.20.0.3:35074 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  20 | root        | 172.20.0.3:35076 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  21 | root        | 172.20.0.3:35078 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  22 | root        | 172.20.0.3:35080 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  23 | root        | 172.20.0.3:35082 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  24 | root        | 172.20.0.3:35084 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  25 | root        | 172.20.0.3:35086 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  26 | root        | 172.20.0.3:35088 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  27 | root        | 172.20.0.3:35090 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  28 | root        | 172.20.0.3:35092 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  29 | root        | 172.20.0.3:35094 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  30 | root        | 172.20.0.3:35096 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  31 | root        | 172.20.0.3:35098 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  32 | root        | 172.20.0.3:35100 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  33 | root        | 172.20.0.3:35102 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  34 | root        | 172.20.0.3:35104 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  35 | root        | 172.20.0.3:35106 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  36 | root        | 172.20.0.3:35108 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  37 | root        | 172.20.0.3:35110 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  38 | root        | 172.20.0.3:35112 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  39 | root        | 172.20.0.3:35114 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  40 | root        | 172.20.0.3:35116 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  41 | root        | 172.20.0.3:35118 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  42 | root        | 172.20.0.3:35120 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  43 | root        | 172.20.0.3:35122 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  44 | root        | 172.20.0.3:35124 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  45 | root        | 172.20.0.3:35126 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  46 | root        | 172.20.0.3:35128 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  47 | root        | 172.20.0.3:35130 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  48 | root        | 172.20.0.3:35132 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  49 | root        | 172.20.0.3:35134 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  50 | root        | 172.20.0.3:35136 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  51 | root        | 172.20.0.3:35138 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  52 | root        | 172.20.0.3:35140 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  53 | root        | 172.20.0.3:35142 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  54 | root        | 172.20.0.3:35144 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  55 | root        | 172.20.0.3:35146 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  56 | root        | 172.20.0.3:35148 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  57 | root        | 172.20.0.3:35150 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  58 | root        | 172.20.0.3:35152 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  59 | root        | 172.20.0.3:35154 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  60 | root        | 172.20.0.3:35156 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  61 | root        | 172.20.0.3:35158 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  62 | root        | 172.20.0.3:35160 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  63 | root        | 172.20.0.3:35162 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  64 | root        | 172.20.0.3:35164 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  65 | root        | 172.20.0.3:35166 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  66 | root        | 172.20.0.3:35168 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  67 | root        | 172.20.0.3:35170 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  68 | root        | 172.20.0.3:35172 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  69 | root        | 172.20.0.3:35174 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  70 | root        | 172.20.0.3:35176 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  71 | root        | 172.20.0.3:35178 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  72 | root        | 172.20.0.3:35180 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  73 | root        | 172.20.0.3:35182 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  74 | root        | 172.20.0.3:35184 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  75 | root        | 172.20.0.3:35186 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  76 | root        | 172.20.0.3:35188 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  77 | root        | 172.20.0.3:35190 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  78 | root        | 172.20.0.3:35192 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  79 | root        | 172.20.0.3:35194 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  80 | root        | 172.20.0.3:35196 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  81 | root        | 172.20.0.3:35198 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  82 | root        | 172.20.0.3:35200 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  83 | root        | 172.20.0.3:35202 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  84 | root        | 172.20.0.3:35204 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  85 | root        | 172.20.0.3:35206 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  86 | root        | 172.20.0.3:35208 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  87 | root        | 172.20.0.3:35210 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  88 | root        | 172.20.0.3:35212 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  89 | root        | 172.20.0.3:35214 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  90 | root        | 172.20.0.3:35216 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  91 | root        | 172.20.0.3:35218 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  92 | root        | 172.20.0.3:35220 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  93 | root        | 172.20.0.3:35222 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  94 | root        | 172.20.0.3:35224 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  95 | root        | 172.20.0.3:35226 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  96 | root        | 172.20.0.3:35228 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  97 | root        | 172.20.0.3:35230 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  98 | root        | 172.20.0.3:35232 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
|  99 | root        | 172.20.0.3:35234 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
| 100 | root        | 172.20.0.3:35236 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
| 101 | root        | 172.20.0.3:35238 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
| 102 | root        | 172.20.0.3:35240 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
| 103 | root        | 172.20.0.3:35242 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
| 104 | root        | 172.20.0.3:35244 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
| 105 | root        | 172.20.0.3:35246 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
| 106 | root        | 172.20.0.3:35248 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
| 107 | root        | 172.20.0.3:35250 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
| 108 | root        | 172.20.0.3:35252 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
| 109 | root        | 172.20.0.3:35254 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
| 110 | root        | 172.20.0.3:35256 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
| 111 | root        | 172.20.0.3:35258 | oncostore | Sleep   |   18 |                          | NULL             |    0.000 |
+-----+-------------+------------------+-----------+---------+------+--------------------------+------------------+----------+
106 rows in set (0.001 sec)
```

Thanks for your time.

Cheers,
Dominik

**Comment by christopher-mohr** [comment]
Hi Dominik, thanks for reporting this. I had the same issue before but couldn't identify the cause so far. I was also checking for open connections for unclosed connections e.g.

I will further investigate this issue.

**Comment by christopher-mohr** [comment]
Hi @muellerdo, are you still working on this? If so, could you test it with the first stable [release](https://github.com/qbicsoftware/variantstore-service/releases/tag/1.0.0) and check if the error still occurs?

**Comment by muellerdo** [comment]
Hey @christopher-mohr,

sorry for the late reply.

I'm currently in a strict grip of other projects, but I am quite curious and going to have a look to find some time next week for performing an independent setup of the first stable release.

I will keep your updated and will send you some feedback per mail or via GitHub.

Cheers,
Dominik

**Comment by christopher-mohr** [comment]
Thanks for your reply! It would be great if you could test it with the release at some point.

**Comment by christopher-mohr** [comment]
According to @muellerdo this did not occur when using release [1.0.0](https://github.com/qbicsoftware/variantstore-service/releases/tag/1.0.0). Thanks for the feedback!
