### ISSUE TITLE
Improve documentation and error handling for VCF import

### ISSUE THREAD

**Issue by christopher-mohr** [qbicsoftware/variantstore-service#40]
If the metadata is not provided in the right way when using the multiform VCF import, one will get an error like the following:

```
...
variantstore_app | Caused by: groovy.lang.MissingPropertyException: No such property: is_somatic for class: java.lang.String
variantstore_app | 	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:65)
variantstore_app | 	at org.codehaus.groovy.runtime.callsite.GetEffectivePojoPropertySite.getProperty(GetEffectivePojoPropertySite.java:65)
variantstore_app | 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:298)
variantstore_app | 	at life.qbic.variantstore.parser.MetadataReader.parseIsSomatic(MetadataReader.groovy:47)
variantstore_app | 	at life.qbic.variantstore.parser.MetadataReader$parseIsSomatic.callStatic(Unknown Source)
variantstore_app | 	at life.qbic.variantstore.parser.MetadataReader.<init>(MetadataReader.groovy:34)
variantstore_app | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
variantstore_app | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
variantstore_app | 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
variantstore_app | 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
variantstore_app | 	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:80)
variantstore_app | 	at 
...
```

We should extend the documentation and provide an example on how to upload VCF files and metadata to make it clear. Additionally, we should provide more descriptive error messages in such cases.

**Comment by christopher-mohr** [comment]
Resolved by https://github.com/qbicsoftware/variantstore-service/commit/30f81633df1edf8e6e82f6e03b00f01fc4071b81.
