### ISSUE TITLE
Gene information (.gff3) upload fails due to missing gene constructor

### ISSUE THREAD

**Issue by christopher-mohr** [qbicsoftware/variantstore-service#41]
The upload of gene information in `gff3` format currently fails due to a missing empty `Gene` constructor.

```
Mar 22 17:23:41 oncostore-db-proto start_varianstore_jar.sh: 17:23:41.201 [pool-2-thread-677] ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: Could not find matching constructor for: life.qbic.variantstore.model.Gene()
Mar 22 17:23:41 oncostore-db-proto start_varianstore_jar.sh: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: life.qbic.variantstore.model.Gene()
Mar 22 17:23:41 oncostore-db-proto start_varianstore_jar.sh: at groovy.lang.MetaClassImpl.invokeConstructor(MetaClassImpl.java:1749)
Mar 22 17:23:41 oncostore-db-proto start_varianstore_jar.sh: at groovy.lang.MetaClassImpl.invokeConstructor(MetaClassImpl.java:1556)
Mar 22 17:23:41 oncostore-db-proto start_varianstore_jar.sh: at org.codehaus.groovy.runtime.callsite.MetaClassConstructorSite.callConstructor(MetaClassConstructorSite.java:46)
Mar 22 17:23:41 oncostore-db-proto start_varianstore_jar.sh: at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
Mar 22 17:23:41 oncostore-db-proto start_varianstore_jar.sh: at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:237)
Mar 22 17:23:41 oncostore-db-proto start_varianstore_jar.sh: at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:241)
Mar 22 17:23:41 oncostore-db-proto start_varianstore_jar.sh: at life.qbic.variantstore.parser.EnsemblParser.<init>(EnsemblParser.groovy:61)
```

This probably happened due to last changes before the release and should be covered by tests.

**Comment by christopher-mohr** [comment]
Fixed by #43.
